### ISSUE TITLE
More specific infra labels

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt-pr-bot#12]
We have a bunch of more specific labels we could use in addition to `infra` for a lot of the tools:

 * Changes in tools/lint should have the `lint` label
 * Changes in tools/manifest should have the `manifest` label
 * Changes in tools/runner should have the `runner` label
 * Changes in tools/wptrunner should have the `wptrunner` label
 * Changes in tools/wptserve should have the `wptserve` label (@jgraham should we include tools/serve here too?)
 * Changes in tools/wpt should have the `wpt` label
 * Changes to resources/testharness.* or testharnessreport.* (files!) should have the `testharness.js` label
 * Changes to resources/testdriver.* or testdriver-vendor.* (files!) should have the `testdriver.js` label
 * Changes to resources/idlharness.* (files!) should have the `idlharness.js` label
 * Changes to css/tools should have the `css-build-system` label

These need some code changes, so aren't just adding things to arrays. Bah! :(

**Comment by tobie** [comment]
Yeah, that'll need a bit of coding.

**Comment by jugglinmike** [comment]
@gsnedders instead of `css-build-system`, how about `css` and `infra`? And is there any reason not to add `css` for all modifications to files within the `css` directory?

**Comment by jugglinmike** [comment]
Resolved via gh-36
