### ISSUE TITLE
Move wpt-pr-bot to be hosted on App Engine

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt-pr-bot#128]
In order to consolidate wpt-related projects into one location, I plan to move wpt-pr-bot from its current home on Heroku (maintained by Bocoup) to run on App Engine (maintained by Google).

There is currently an 'appengine' branches with the following changes:

1. Add a `--dry-run` mode.
1. Add support for deploying to App Engine, including reading secrets from the datastore if available (falling back to reading from the env as before).
1. Some not well understood changes to `.github/workflows/test.yml` relating to Node version.

wpt-ptr-bot is currently running on App Engine in `--dry-run` mode, off the 'appengine' branch, and GitHub has been sending it webhook notifications for ~1 week. Based on logs + github webhook delivery notifications, I think it will do the right thing, though it's obviously hard to be sure.

In terms of the path forward, https://github.com/web-platform-tests/wpt-pr-bot/compare/appengine has the diff between 'master' and 'appengine'. My plan is to send a PR of the appengine changes to master, reducing the appengine branch to just adding the `--dry-run` flag to startup params (and resolving the changes to `.github/workflows/test.yml` during the PR). At that point the switchover would be a case of:

1. Turn off the webhook to the App Engine version of wpt-pr-bot.
1. Deploy the master branch of the repository to App Engine.
1. Turn off the webhook to the Heroku version of wpt-pr-bot and turn on the webhook to the App Engine version.
1. Monitor everything carefully.

The Heroku version will be kept online but doing nothing for a while (a week?) to give us a fallback in case App Engine goes mad.

My current goal is to do the switchover early next week.

**Comment by stephenmcgruer** [comment]
FYI @foolip @zcorpan

**Comment by stephenmcgruer** [comment]
I have now merged `appengine` (or the useful parts) into `master`. A little unexpectedly (I didn't know this was automatic), the Heroku instance has picked up the commit, built it, and redeployed.

I'm going to let that soak over the weekend, then will attempt a first migration on Monday morning EST.

**Comment by stephenmcgruer** [comment]
I am now beginning a first attempt at migration. 

* [X] Turn off the webhook to the App Engine version of wpt-pr-bot.
* [ ] Deploy the master branch of the repository to App Engine.
* [ ] Turn off the webhook to the Heroku version of wpt-pr-bot and turn on the webhook to the App Engine version.
* [ ] Monitor everything carefully.

**Comment by stephenmcgruer** [comment]
So far so good. We discovered that the token permissions were wrong, which necessitated me intervening manually in https://github.com/web-platform-tests/wpt/pull/20788. It was a small fix for the token however, and it worked correctly in a subsequent chromium export.

**Comment by stephenmcgruer** [comment]
At this point, wpt-pr-bot has been running on AppEngine for a week without any known issues. I am closing this as fixed; @zcorpan I suggest you look into turning down the Heroku instance.

**Comment by zcorpan** [comment]
I've stopped the dyno and disabled auto deploy.

Thanks!
