### ISSUE TITLE
TypeError when processing WebKit-exported pull requests

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt-pr-bot#156]
cc @clopez

In https://github.com/web-platform-tests/wpt/pull/24748, a WebKit-exported pull request was made to WPT, but wpt-pr-bot didn't comment on it. Near the same time, I received an appengine alert for a crash:

```
TypeError: Cannot read property 'length' of null
at getMetadata (/workspace/lib/metadata/index.js:117)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97)
```

Looking at the code, it is on this line:

```
    if (webkit.related(metadata.title)) {
        var titleWebkitIssueMatch = metadata.title.match(/.*https:\/\/bugs.webkit.org\/show_bug.cgi\?id=(\d+).*/i);
        if (titleWebkitIssueMatch.length == 2) {
```

Notice that the regex calls for `https`, but the GH pull request uses `http`. This will cause the match to fail and so titleWebkitIssueMatch will be undefined.

We should fix the regex to not require https, but this likely comes from the instructions at https://trac.webkit.org/wiki/WPTExportProcess instructing folks to use http for the title.

**Comment by Loirooriol** [comment]
> this likely comes from the instructions at https://trac.webkit.org/wiki/WPTExportProcess instructing folks to use http for the title.

That was the case indeed.

**Comment by clopez** [comment]
I have fixed the instructions at https://trac.webkit.org/wiki/WPTExportProcess to instruct using `https://`
