### ISSUE TITLE
Be smart about changes to OWNERS files

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt-pr-bot#16]
The bot could be smart about changing OWNERS files and request review from those added/removed.

Example:  https://github.com/w3c/web-platform-tests/pull/10508#issuecomment-382043566

**Comment by tobie** [comment]
This would become a security vulnerability if ever there was a merge bot added to the project.

**Comment by zcorpan** [comment]
I think we can remove the OWNERS code from the bot when the lint has landed. This issue is also sort of moot now that almost everything has OWNERS.

**Comment by zcorpan** [comment]
Forgot about this issue and filed https://github.com/web-platform-tests/wpt-pr-bot/issues/32

@tobie so, we'd need to exclude review requests from bot accounts?
