### ISSUE TITLE
Update bot to create a new label for WebDriver BiDi

### ISSUE THREAD

**Issue by whimboo** [web-platform-tests/wpt-pr-bot#168]
I would like to see a new label being created for the new WebDriver BiDi spec related tests. Right it's planned to get them landed under `webdriver/tests/bidi/`.

As @jgraham mentioned the bot should be updated to recognize this folder as separate from `webdriver`.

**Comment by stephenmcgruer** [comment]
I've pushed the new version, looks a positive test works at least (https://github.com/web-platform-tests/wpt/pull/27932).

**Comment by whimboo** [comment]
Thanks @stephenmcgruer!
