### ISSUE TITLE
Share a bot account for all wpt-related bots?

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt-pr-bot#17]
@lukebjerring needs a bot account to post comments like https://github.com/web-platform-tests/wpt.fyi/pull/67#issuecomment-382505666.

On the main repo we have w3c-bots posting like this: https://github.com/w3c/web-platform-tests/pull/10280#issuecomment-378272797. The name of that bot won't make sense after the repo migration.

Should we have a single bot, and how should we share credentials or tokens for it?

@tobie @jgraham @jugglinmike @sideshowbarker

**Comment by foolip** [comment]
@jugglinmike I think you were right, the pulls bot hasn't been commenting in a while. And yet I haven't seen any outcry, suggesting that maybe it wasn't that useful in its current form. Was that stuff set up by Bocoup, if we do want to revive it?

**Comment by tobie** [comment]
> Should we have a single bot, and how should we share credentials or tokens for it?

So there's logic in the wpt-pr-bot's code base that relies on the all comments made by the bot originating from that code base. This could be fixed, obviously, but would require some work.

If the plan is to move towards GH apps rather than bots (as it should be for both security and GH ToS compliance reasons), then using a single bot also seems like a step in the wrong direction.

**Comment by jgraham** [comment]
@tobie I'm curious why apps means that having a single codebase for all the bot features we want (I assume this excludes external integrations) doesn't make sense?

In general I'm a fan  of shared infrastructure being as shared as possible, and historically when we've had N bots we've had N sets of credentials and no common set of people with access to all the bots. So I'm pretty interested in anything we can do that makes this infrastructure more robust against people moving on to work on different things.

**Comment by tobie** [comment]
Oh, migrating everything into a single app is also possible. But that’s a lot more work.

**Comment by jugglinmike** [comment]
> @jugglinmike I think you were right, the pulls bot hasn't been commenting in a while. And yet I haven't seen any outcry, suggesting that maybe it wasn't that useful in its current form. Was that stuff set up by Bocoup, if we do want to revive it?

That bot was set up at Bocoup. Judging from https://pulls.web-platform-tests.org/, it hasn't reacted to a pull request in three days. However, there was also an apparent outage between the 9th and 16th of this month, so it may technically be deployed but suffering from some other problem.

I would love to investigate! This may take some doing, though. I need to get a copy of the credentials, and I may need someone to bootstrap me into the system. I've put out a few feelers along these lines.

> Oh, migrating everything into a single app is also possible. But that’s a lot more work.

I'd be down to do this

**Comment by zcorpan** [comment]
@lukebjerring's bot for wpt.fyi has been replaced with @wpt-pr-bot. 

@w3c-bots currently doesn't post comments; when we want to resurrect something like it we can use @wpt-pr-bot instead.

Are there other bots?

**Comment by foolip** [comment]
I don't think there are any others.

**Comment by foolip** [comment]
So fixed, thank you!
