### ISSUE TITLE
Invite OWNERS to web-platform-tests/reviewers team instead of web-platform-tests/wpt repo

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt-pr-bot#21]
See discussion at https://w3.logbot.info/testing/20180528#c409484 for what the bot is currently doing.

An alternative would be to gate changes to OWNERS files on people being in the reviewers team, and having humans do it. @jgraham?

**Comment by zcorpan** [comment]
I prefer the latter, and have the bot just request review. See #32.

**Comment by foolip** [comment]
wpt-pr-bot isn't currently doing any inviting at all, closing.
