### ISSUE TITLE
Where are the logs?

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt-pr-bot#240]
The bot has various logging calls throughout, and I presume there are logs stored *somewhere* for the live instance—where are they?

Taking a quick look, I couldn't see why https://github.com/web-platform-tests/wpt/pull/43678 didn't get approved by the poller.

**Comment by cookiecrook** [comment]
FYI that one is going to get rolled back for unrelated reasons.

**Comment by foolip** [comment]
Unfortunately the logs show up in GCP only. cc @past

**Comment by past** [comment]
I can provide logs if needed. I'll close this ticket, but feel free to ping me in the future.
