### ISSUE TITLE
Test suite does not function in Node versions 9 or 10

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt-pr-bot#29]
The test suite depends on the "replay" module, and that module has a bug which interferes with HTTPS request mocking in Node.js versoins 9 and 10:

https://github.com/assaf/node-replay/issues/141

We're going to tolerate this for now because the problem does not effect the LTS release of Node.js and because it's limited to the test suite (i.e. not the application code). This project's dependency on the "replay" module should be updated once the underlying bug is corrected.

**Comment by foolip** [comment]
My `node --version` is v10.15.3 and it now works for me. Locally I get 59 passing tests just like in https://travis-ci.com/web-platform-tests/wpt-pr-bot/builds/135356662.

Was this the only think blocking an upgrade?

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt-pr-bot/pull/116 also shows that it works, so I'll close this.
