### ISSUE TITLE
Need to stop adding >100 labels to an issue

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/wpt-pr-bot#35]
GitHub are limiting the number of labels on an issue to 100 as a workaround for their performance issues with large numbers of labels. In practice we only see that many labels on large refactors that are typially not interesting to the people following specific specs, so it would be acceptable just to label such PRs as infra and ignore the directory based labels.

This change will take effect on July 26th, so we need a solution before then.

**Comment by foolip** [comment]
Adding this many labels and reviewers is merely a nuisance, so this seems like a good thing! Perhaps when too many directories are touched, we just fall back to no labels, or some infra label?
