### ISSUE TITLE
wpt-pr-bot should respond to POSTs from the wpt.fyi revision announcer

### ISSUE THREAD

**Issue by mdittmer** [web-platform-tests/wpt-pr-bot#41]
There is a desire to trigger TaskCluster builds on regular intervals iff a new revision has been announced by the announcer. In conversation with @foolip and @jgraham, the following scheme has been devised

1. wpt.fyi revision announcer discovers new revision for Epoch X (where TaskCluster cares about Epoch X);
1. Announcer `POST`s to a URL owned by wpt-pr-bot, which has WPT push credentials;
1. wpt-pr-bot responds to the POST by updating a branch to the newly announced revision;
1. The branch update triggers a TaskCluster build.

In this repo, the following work needs to be done:

- [ ] Establish endpoint(s) that accept POSTs from wpt.fyi revision announcer
- [ ] Write business logic to respond to POSTs by updating a branch

This issue depends on https://github.com/web-platform-tests/wpt.fyi/issues/551

**Comment by mdittmer** [comment]
@foolip and @jgraham how should wpt-pr-bot authenticate requests from the announcer?

**Comment by jgraham** [comment]
Can't both ends just have a secret token that's passed in the POST request (assuming that's https)?

**Comment by foolip** [comment]
Yeah, that's similar to how GitHub webhooks (can be) authenticated, where GitHub uses a shared secret to compute a digest of the message, and the client does the same to cross-check. In that model the secret is never sent over the wire.

Here, however, we don't need to authenticate, wpt-pr-bot could simply go check https://wpt.fyi/api/ and ignore everything about the webhook, having it only as a trigger.

**Comment by lukebjerring** [comment]
@mdittmer is this issue resolved?

**Comment by mdittmer** [comment]
This is resolved:obsolete. We went with a polling strategy that does not
require push to wpt-pr-bot.
