### ISSUE TITLE
Do not react to closed pull requests

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt-pr-bot#53]
This project updates pull requests when they are closed. That event does not indicate any meaningful change, but in rare cases (e.g. [WPT pull request 12553](https://github.com/web-platform-tests/wpt/pull/12553#event-1974862210)) it may cause the script to make irrelevant modifications to the pull request. The "closed" event ought to be ignored.

**Comment by foolip** [comment]
I think this is a dupe of https://github.com/web-platform-tests/wpt-pr-bot/issues/38.
