### ISSUE TITLE
Support some notion of "WIP"

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt-pr-bot#58]
Authors should be able to mark a PR as WIP and the bot shouldn't assign reviewers until the PR is out of the WIP state. I think we can reuse the existing "do not merge yet" label for this purpose.

**Comment by Hexcles** [comment]
WIP: work in progress

**Comment by gsnedders** [comment]
Remember that only people with write access can set labels, but that's probably good enough in this case.

**Comment by zcorpan** [comment]
An alternative is to look for "WIP" in the PR title. The bot could further add (and remove) the "do not merge yet" label based on the PR title.

**Comment by foolip** [comment]
This works after https://github.com/web-platform-tests/wpt-pr-bot/issues/69 was resolved.
