### ISSUE TITLE
epochs/six_hourly branch was updated too late

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt-pr-bot#74]
In https://github.com/web-platform-tests/wpt/issues/17342#issuecomment-521532932 I found that the epochs/six_hourly branch in wpt wasn't updated until 06:32, where it should be updated as soon as possible after 06:00 UTC, and every other multiple of 6 hours in UTC.

@jugglinmike are there logs for wpt-pr-bot that could confirm when it first tried to update the epochs branches? What is the trigger for that logic currently, and how reliable is it?

**Comment by jugglinmike** [comment]
Yup, logs are available through the Heroku interface. (WPT doesn't have a mechanism for sharing secrets, so anyone wanting access will have to contact me for the credentials--sorry!)

<details>
  <summary>The logs for 6:00 UTC show that the branch was updated at that time</summary>

    Aug 15 06:00:08 wpt-pr-bot app/web.1: Updating epoch weekly 
    Aug 15 06:00:08 wpt-pr-bot app/web.1: Updating epoch daily 
    Aug 15 06:00:08 wpt-pr-bot app/web.1: Updating epoch twelve_hourly 
    Aug 15 06:00:08 wpt-pr-bot app/web.1: Updating epoch six_hourly 
    Aug 15 06:00:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/daily 
    Aug 15 06:00:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/weekly 
    Aug 15 06:00:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/twelve_hourly 
    Aug 15 06:00:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/six_hourly 
    Aug 15 06:00:09 wpt-pr-bot app/web.1: Error updating epoch daily  
    Aug 15 06:00:09 wpt-pr-bot app/web.1:  Error: Expected ref hash to have changed, but it has not 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at github.get.then.github.post.ref (/app/lib/epochs.js:57:23) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at _fulfilled (/app/node_modules/q/q.js:797:54) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at self.promiseDispatch.done (/app/node_modules/q/q.js:826:30) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:759:13) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at /app/node_modules/q/q.js:573:44 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at flush (/app/node_modules/q/q.js:108:17) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:132:7) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at process._tickCallback (internal/process/next_tick.js:181:9) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1: PATCH https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/six_hourly 
    Aug 15 06:00:09 wpt-pr-bot app/web.1: {"sha":"0c69b971f41f48daf39199963f96af76a9ad7fb2","force":true} 
    Aug 15 06:00:09 wpt-pr-bot app/web.1: Error updating epoch twelve_hourly  
    Aug 15 06:00:09 wpt-pr-bot app/web.1:  Error: Expected ref hash to have changed, but it has not 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at github.get.then.github.post.ref (/app/lib/epochs.js:57:23) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at _fulfilled (/app/node_modules/q/q.js:797:54) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at self.promiseDispatch.done (/app/node_modules/q/q.js:826:30) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:759:13) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at /app/node_modules/q/q.js:573:44 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at flush (/app/node_modules/q/q.js:108:17) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:132:7) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at process._tickCallback (internal/process/next_tick.js:181:9) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1: Error updating epoch weekly  
    Aug 15 06:00:09 wpt-pr-bot app/web.1:  Error: Expected ref hash to have changed, but it has not 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at github.get.then.github.post.ref (/app/lib/epochs.js:57:23) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at _fulfilled (/app/node_modules/q/q.js:797:54) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at self.promiseDispatch.done (/app/node_modules/q/q.js:826:30) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:759:13) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at /app/node_modules/q/q.js:573:44 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at flush (/app/node_modules/q/q.js:108:17) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:132:7) 
    Aug 15 06:00:09 wpt-pr-bot app/web.1:     at process._tickCallback (internal/process/next_tick.js:181:9) 
    Aug 15 06:00:10 wpt-pr-bot app/web.1: Updated epoch six_hourly 0c69b971f41f48daf39199963f96af76a9ad7fb2 

</details>

Here are the commit details:

    $ TZ=UTC git log -n1 --date=local --format=fuller 0c69b971f41f48daf39199963f96af76a9ad7fb2
    commit 0c69b971f41f48daf39199963f96af76a9ad7fb2
    Author:     Wanming Lin <wanming.lin@intel.com>
    AuthorDate: Thu Aug 15 03:02:25 2019
    Commit:     Blink WPT Bot <blink-w3c-test-autoroller@chromium.org>
    CommitDate: Thu Aug 15 03:24:30 2019

        [webnfc] Enable wpt tests with mock nfc implementation

<details>
  <summary>The next round of logs show that the system was stable</summary>

    Aug 15 06:02:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/six_hourly 
    Aug 15 06:02:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/daily 
    Aug 15 06:02:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/twelve_hourly 
    Aug 15 06:02:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/weekly 
    Aug 15 06:02:09 wpt-pr-bot app/web.1: Error updating epoch six_hourly  
    Aug 15 06:02:09 wpt-pr-bot app/web.1:  Error: Expected ref hash to have changed, but it has not 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at github.get.then.github.post.ref (/app/lib/epochs.js:57:23) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at _fulfilled (/app/node_modules/q/q.js:797:54) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at self.promiseDispatch.done (/app/node_modules/q/q.js:826:30) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:759:13) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at /app/node_modules/q/q.js:573:44 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at flush (/app/node_modules/q/q.js:108:17) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:132:7) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at process._tickCallback (internal/process/next_tick.js:181:9) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1: Error updating epoch twelve_hourly  
    Aug 15 06:02:09 wpt-pr-bot app/web.1:  Error: Expected ref hash to have changed, but it has not 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at github.get.then.github.post.ref (/app/lib/epochs.js:57:23) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at _fulfilled (/app/node_modules/q/q.js:797:54) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at self.promiseDispatch.done (/app/node_modules/q/q.js:826:30) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:759:13) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at /app/node_modules/q/q.js:573:44 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at flush (/app/node_modules/q/q.js:108:17) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:132:7) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at process._tickCallback (internal/process/next_tick.js:181:9) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1: Error updating epoch weekly  
    Aug 15 06:02:09 wpt-pr-bot app/web.1:  Error: Expected ref hash to have changed, but it has not 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at github.get.then.github.post.ref (/app/lib/epochs.js:57:23) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at _fulfilled (/app/node_modules/q/q.js:797:54) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at self.promiseDispatch.done (/app/node_modules/q/q.js:826:30) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:759:13) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at /app/node_modules/q/q.js:573:44 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at flush (/app/node_modules/q/q.js:108:17) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:132:7) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at process._tickCallback (internal/process/next_tick.js:181:9) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1: Error updating epoch daily  
    Aug 15 06:02:09 wpt-pr-bot app/web.1:  Error: Expected ref hash to have changed, but it has not 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at github.get.then.github.post.ref (/app/lib/epochs.js:57:23) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at _fulfilled (/app/node_modules/q/q.js:797:54) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at self.promiseDispatch.done (/app/node_modules/q/q.js:826:30) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:759:13) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at /app/node_modules/q/q.js:573:44 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at flush (/app/node_modules/q/q.js:108:17) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:132:7) 
    Aug 15 06:02:09 wpt-pr-bot app/web.1:     at process._tickCallback (internal/process/next_tick.js:181:9) 

</details>

<details>
  <summary>...but jumping forward to 06:32, it looks like the branch was updated <em>again</em></summary>

    Aug 15 06:32:09 wpt-pr-bot app/web.1: Updating epoch weekly 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: Updating epoch daily 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: Updating epoch twelve_hourly 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: Updating epoch six_hourly 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/twelve_hourly 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: Error updating epoch twelve_hourly  
    Aug 15 06:32:09 wpt-pr-bot app/web.1:  Error: Expected ref hash to have changed, but it has not 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at github.get.then.github.post.ref (/app/lib/epochs.js:57:23) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at _fulfilled (/app/node_modules/q/q.js:797:54) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at self.promiseDispatch.done (/app/node_modules/q/q.js:826:30) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:759:13) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at /app/node_modules/q/q.js:573:44 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at flush (/app/node_modules/q/q.js:108:17) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:132:7) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at process._tickCallback (internal/process/next_tick.js:181:9) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/weekly 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/six_hourly 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/daily 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: Error updating epoch weekly  
    Aug 15 06:32:09 wpt-pr-bot app/web.1:  Error: Expected ref hash to have changed, but it has not 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at github.get.then.github.post.ref (/app/lib/epochs.js:57:23) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at _fulfilled (/app/node_modules/q/q.js:797:54) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at self.promiseDispatch.done (/app/node_modules/q/q.js:826:30) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:759:13) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at /app/node_modules/q/q.js:573:44 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at flush (/app/node_modules/q/q.js:108:17) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:132:7) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at process._tickCallback (internal/process/next_tick.js:181:9) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: PATCH https://api.github.com/repos/web-platform-tests/wpt/git/refs/heads/epochs/six_hourly 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: {"sha":"b16bc5597bb9981c3bd29ca3209979df0c9c24fe","force":true} 
    Aug 15 06:32:09 wpt-pr-bot app/web.1: Error updating epoch daily  
    Aug 15 06:32:09 wpt-pr-bot app/web.1:  Error: Expected ref hash to have changed, but it has not 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at github.get.then.github.post.ref (/app/lib/epochs.js:57:23) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at _fulfilled (/app/node_modules/q/q.js:797:54) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at self.promiseDispatch.done (/app/node_modules/q/q.js:826:30) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:759:13) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at /app/node_modules/q/q.js:573:44 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at flush (/app/node_modules/q/q.js:108:17) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:132:7) 
    Aug 15 06:32:09 wpt-pr-bot app/web.1:     at process._tickCallback (internal/process/next_tick.js:181:9) 
    Aug 15 06:32:10 wpt-pr-bot app/web.1: Updated epoch six_hourly b16bc5597bb9981c3bd29ca3209979df0c9c24fe 

</details>

And the commit details:

    $ TZ=UTC git log -n1 --date=local --format=fuller b16bc5597bb9981c3bd29ca3209979df0c9c24fe
    commit b16bc5597bb9981c3bd29ca3209979df0c9c24fe
    Author:     Philip Jägenstedt <philip@foolip.org>
    AuthorDate: Thu Aug 15 05:57:12 2019
    Commit:     GitHub <noreply@github.com>
    CommitDate: Thu Aug 15 05:57:12 2019

        [Azure Pipelines] Migrate scheduled builds to YAML (#18442)

As a refresher, to retrieve the "revision of interest" for each "epoch" this script [queries](https://github.com/web-platform-tests/wpt-pr-bot/blob/a352e4a55f0f8842fb9ac1cc7b01fecbd1d9d752/lib/epochs.js#L10) the revision announce at https://wpt.fyi/api/revisions/latest on [a 2-minute interval](https://github.com/web-platform-tests/wpt-pr-bot/blob/a352e4a55f0f8842fb9ac1cc7b01fecbd1d9d752/index.js#L176).

So now the questions are:

- Why wasn't the latest commit served by the revision announcer at 6:00 UTC?
- Why did the revision announcer change its selection for the "6 hourly" epoch at 6:32 UTC?

@mdittmer or @Hexcles: can either of you make any guesses?

**Comment by foolip** [comment]
Interesting, might we be looking at a race condition here. https://wpt.fyi/api/revisions/list?epochs=six_hourly&num_revisions=10 currently doesn't list 0c69b971f41f48daf39199963f96af76a9ad7fb2. The logs in https://github.com/web-platform-tests/wpt-pr-bot/issues/74#issuecomment-521717263 make it pretty clear that the commit was returned then, so that's a bug.

It's worth noting how close to 6:00 UTC the correct commit was, less than 3 minutes before. If there's a propagation delay anywhere, or unintended caching, then the revision announcer may have observed the time being past 6:00 UTC without seeing the most recent commit.

I'll file a wpt.fyi issue.

**Comment by foolip** [comment]
I've filed https://github.com/web-platform-tests/wpt.fyi/issues/1416.

@jugglinmike just to confirm, wpt-pr-bot polled the wpt.fyi API every two minutes between 6:00 and 6:32 UTC and only at the end of that interval did wpt.fyi start returning the correct commit?

**Comment by jugglinmike** [comment]
That's correct. I'd share the complete log, but the system (or at least, our free account within it) doesn't seem to offer export.

**Comment by jugglinmike** [comment]
Here are the logs (manually extracted from the web interface):

https://gist.github.com/jugglinmike/d115f066d2c934a69c608d62dbe5c7ff

Search for "force", and you'll see all instances of git ref updates.

**Comment by foolip** [comment]
After https://github.com/web-platform-tests/wpt/pull/18631 this manifests differently, more visible. In https://wpt.fyi/runs we can see that two consecutive commits, dbb4e0ccfd and 49b0aca116, both got Edge/Safari results. The two builds for those were:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28811
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28812

Both were triggered by updates to the epochs/six_hourly branch only minutes apart.

**Comment by foolip** [comment]
The good thing about the new behavior is that we'll get runs from the desired commits even when epochs/six_hourly points at the wrong thing for a time. The bad part is it wastes resources, especially for Edge there aren't enough VMs to run everything in parallel, so the VMs will be busy and it won't be possible to debug issues using them right then.

**Comment by foolip** [comment]
I've proposed https://github.com/web-platform-tests/wpt/issues/19322 to address this.
