### ISSUE TITLE
Unable to dismiss reviewer

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt-pr-bot#9]
For some directories, there's a bunch of different stuff in there and I'm not competent to review all of it, so I sometimes want to dismiss myself as a reviewer. However, when there's another push to the branch wpt-pr-bot readds me as a reviewer because I appear in a OWNERS file.

**Comment by tobie** [comment]
Just saw this today. Sorry.

I don't have a quick fix for this, tbh.

**Comment by zcorpan** [comment]
I see two ways to fix this.

* Scrape the HTML of the pull request, looking for removed review requests.
* Listen to https://developer.github.com/v3/activity/events/types/#pullrequestevent and record somehow that the review request was removed.
* `GET /repos/:owner/:repo/pulls/:number/requested_reviewers` and avoid asking for more review requests if that is non-empty (but this would also not add the suggested reviewers if the PR author adds a review request).

Am I missing anything?

**Comment by gsnedders** [comment]
One more option is to call https://developer.github.com/v3/issues/events/#list-events-for-an-issue and look through the events then, rather than recording somehow when the review request was removed.
